#!/bin/bash
for basename in anno compare-anno; do
    for file in ${basename}.{css,js}; do
        aws --profile kca-s3 s3 cp "$file" "s3://megacomplete.net/anno/$file" --acl public-read
    done
done
